# Setup
title:               WashU Autonomous Racing (WUAIR)
tagline:             'Project Portfolio'
description:         ''
url:                 https://wu-ai-racing.github.io/wu-ai-web/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:             
  name:             "Dayan Parker"
  url:              "https://www.linkedin.com/in/dayanparker"
  email:            "parkerdayan@gmail.com"

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
